### ISSUE TITLE
Runtime error sodium.crypto_sign is not a function

### ISSUE THREAD

**Issue by dmahmouali** [JimberSoftware/pkid-node-client#4]
using version `"@jimber/pkid": "^1.0.4"`

the code
```js
const client = new Pkid(URL, keypair);
client.setDoc(key, value);
```

logs
```
TypeError: sodium.crypto_sign is not a function
    at sign (/home/ayoub/Documents/js-next/grid3_client_ts/node_modules/@jimber/pkid/src/util.js:41:17)
    at signEncode (/home/ayoub/Documents/js-next/grid3_client_ts/node_modules/@jimber/pkid/src/util.js:47:23)
    at Pkid.setDoc (/home/ayoub/Documents/js-next/grid3_client_ts/node_modules/@jimber/pkid/src/index.js:104:26)
    at PKID.set (/home/ayoub/Documents/js-next/grid3_client_ts/src/storage/pkid.ts:31:34)
    at PKID.descriptor.value (/home/ayoub/Documents/js-next/grid3_client_ts/src/storage/utils.ts:6:23)
    at main (/home/ayoub/Documents/js-next/grid3_client_ts/scripts/pkidstore_example.ts:20:24)
    at Object.<anonymous> (/home/ayoub/Documents/js-next/grid3_client_ts/scripts/pkidstore_example.ts:35:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.m._compile (/home/ayoub/.nvm/versions/node/v16.10.0/lib/node_modules/ts-node/src/index.ts:1365:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
```

**Comment by xmonader** [comment]
@jdelrue please check
